FLASK_CONFIG:
  SECRET_KEY: qwer
  HOST: 0.0.0.0
  PORT: 5000
  DEBUG: True
  DB_USERNAME: asdf
  DB_PASSWORD: zxcv
  DB_NAME: qwer
  DB_HOST: 1.1.1.1
  DB_PORT: 3306
  SQLALCHEMY_ECHO: True
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  